Ajo-Savings-Project/ajo-savings

client/src/components/compounds/DashboardHeader/dashboardheader.module.scss, client/src/components/compounds/DashboardHeader/index.tsx, client/src/components/compounds/Sidebar/index.tsx, client/src/components/compounds/Sidebar/sidebar.module.scss, client/src/components/compounds/index.ts, client/src/components/elements/Button/button.module.scss, client/src/components/elements/Typography/index.tsx, client/src/components/elements/Typography/typography.module.scss, client/src/index.css, client/src/layouts/authLayout.tsx, client/src/layouts/dashboardLayout.module.scss, client/src/layouts/dashboardLayout.tsx, client/src/pages/Landing/Header/header.module.scss, client/src/pages/Landing/Header/index.tsx, client/src/styles/_mixins.scss
A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange feedback, and merge!
---
-   [ ] Rebased with master
-   [ ] PR Description provided
-   [ ] Did you communicate these changes with the affected teams?
-   [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
-   [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?
-   [ ] Is this responsive and mobile friendly?
-   [ ] Did you follow the ARIA specs
---
---
=> update project colors

.gitignore
This PR ignores the build folders in FE and BE
**Clickup Task**: [86bwj0d3z](https://app.clickup.com/t/86bwj0d3z)
---
-   [x] Rebased with master
-   [x] PR Description provided
-   [ ] Did you communicate these changes with the affected teams?
-   [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
-   [x] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?
-   [ ] Is this responsive and mobile friendly?
-   [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)
---
---
=> chore: ignore dist folder

README.md
A brief description of what changes your PR introduces. The better this description, the quicker we can review, exchange feedback, and merge!
**Clickup Task**: [ticket code here](link here)
---
-   [ ] Rebased with master
-   [ ] PR Description provided
-   [ ] Did you communicate these changes with the affected teams?
-   [ ] Did unit tests/integration tests/E2E tests get properly added/updated?
-   [ ] Is this change production-ready including testing, feature toggles, configurations, and deployment considerations?
-   [ ] Is this responsive and mobile friendly?
-   [ ] Did you follow the [ARIA specs](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA)
---
---
**Test …
=> chore: add git rebase workflow

client/.husky/pre-commit, client/package.json, client/src/components/elements/TextBox/Select/index.tsx, client/yarn.lock, server/.husky/pre-commit, server/package.json, server/yarn.lock
Add lint staged to format and check code style rules
**Clickup Task**: N/A
---
---
---
=> add lint staged

.github/pull_request_template.md, .gitignore, README.md
This PR updates the github PR template
**Clickup Task**: N/A
---
---
---
=> update PR template

client/src/components/compounds/DashboardHeader/dashboardheader.module.scss, client/src/components/compounds/DashboardHeader/index.tsx, client/src/components/elements/TextBox/Select/index.tsx, client/src/components/elements/TextBox/Select/select.module.scss, client/src/pages/Landing/Header/header.module.scss
- style: prefer extend select style from scss
- style: update padding for header
**ClickUp Task**: N/A
---
---
Before:
After:
---
=> style: header paddings

client/src/components/elements/TextBox/Input/eye-crossed.svg, client/src/components/elements/TextBox/Input/eye.svg, client/src/components/elements/TextBox/Input/index.tsx, client/src/components/elements/TextBox/Input/input.module.scss, client/src/pages/Playground/index.tsx
Added an icon to the password input!
**ClickUp Task**: [CU-#86bwj0cqj](https://app.clickup.com/t/86bwj0cqj)
---
---
---
=> fix: add icon to password input

client/src/pages/Landing/index.tsx
=> fix: add what our user say

client/src/pages/Auth/ResetPassword/index.tsx, client/src/pages/Auth/ResetPassword/layout.tsx, client/src/router/pagesRouter.tsx, client/src/router/routes.ts
=> fix: layout and route

client/src/pages/Landing/WhyUseUs/whyUseUs.module.scss, client/src/pages/Landing/whyUseAjo/whyUseAjo.module.scss
WhyUseUs and WhyUseAjo section padding was adjusted
---
---
---
=> fix: padding added to the sections

client/package.json, client/src/components/autoLogOut.tsx, client/src/components/elements/Button/button.module.scss, client/src/layouts/authLayout.module.scss, client/src/layouts/authLayout.tsx, client/src/layouts/dashboardLayout.tsx, client/src/pages/Auth/Login/login.module.scss, client/src/pages/Auth/ResetPassword/resetPassword.module.scss
=> fix layout

apps/client/src/components/elements/TextBox/Select/index.tsx, apps/client/src/components/elements/TextBox/Select/select.module.scss
=> style: dropdown icon to align with other input

apps/client/src/layouts/authLayout.module.scss
=> fix: add scroll in layout for longer forms

apps/client/src/contexts/authContext.tsx, apps/client/src/pages/Auth/Signup/index.tsx, apps/client/src/pages/Auth/Signup/request.ts
=> feat-sign-up page

apps/server/package.json, apps/server/src/app.ts, apps/server/src/controllers/background-jobs/bullBoardConfig.ts, apps/server/src/controllers/background-jobs/jobs.ts, apps/server/src/controllers/background-jobs/queue.ts, apps/server/src/controllers/background-jobs/worker.ts, apps/server/src/controllers/userController.ts, apps/server/src/models/settings.ts, apps/server/src/models/users.ts, apps/server/src/routes/swaggerSample, apps/server/src/routes/users.ts, apps/server/src/utils/helpers.ts, apps/server/src/utils/mailFunctions.ts, apps/server/src/utils/validation.ts
This PR creates a user sign-up feature
---
---
---
=> feat: add user sign-up feature

apps/client/src/components/compounds/Modal/modal.module.scss
the modal position was adjusted to the center of the page
---
---
---
=> adjust modal scss

apps/client/package.json, apps/client/src/main.tsx, apps/client/src/pages/Playground/index.tsx
Toastify added and accessible globally 
[ CU-86bwqnax8](https://app.clickup.com/t/86bwqnax8)
---
---
---
=> feat: add Toastify

apps/client/package.json, apps/client/src/api/index.ts, apps/client/src/pages/Auth/Login/index.tsx, apps/client/src/pages/Auth/Signup/index.tsx, apps/client/src/pages/Auth/Signup/request.ts, yarn.lock
- connect api
- on successful signup, redirect to login with user email filled and greet user first name
---
---
---
=> feat: connect api

apps/client/src/api/index.ts, apps/client/src/components/compounds/InfoCard/index.tsx, apps/client/src/components/compounds/InfoCard/infoCard.module.scss, apps/client/src/components/compounds/Modal/index.tsx, apps/client/src/components/compounds/Modal/modal.module.scss, apps/client/src/components/elements/appNotify/appnotify.module.scss, apps/client/src/components/elements/appNotify/index.tsx, apps/client/src/components/elements/index.ts, apps/client/src/index.css, apps/client/src/main.tsx, apps/client/src/pages/Auth/ResetPassword/index.tsx, apps/client/src/pages/Auth/ResetPassword/requests.ts, apps/client/src/pages/Auth/Signup/request.ts, apps/client/src/pages/Playground/index.tsx
- improve the toaster ui to match Ajo savings
- improve/update/fix code
---
---
- Error with retry option
- Error only
- Success
- Info
---
=> fix: update notification toaster

apps/server/.env.sample, apps/server/src/backgroundJobs/emailTasks/index.ts, apps/server/src/backgroundJobs/emailTasks/jobs/resetPasswordJob.ts, apps/server/src/backgroundJobs/emailTasks/queues.ts, apps/server/src/backgroundJobs/emailTasks/templates/resetPassword.html, apps/server/src/config/env.ts, apps/server/src/controllers/userController.ts, apps/server/src/models/userPasswordToken.ts, apps/server/src/models/users.ts, apps/server/src/routes/v1/users.ts, apps/server/src/utils/helpers.ts, apps/server/src/utils/validators/index.ts
This PR:
- adds forgot password feature
- updates user model with isVerified, resetToken and resetTokenExpiry fields
- creates a re-usable email function
---
---
---
=> feat: add forgot password feature

.github/workflows/pull_requests.yml, apps/client/src/components/compounds/goal/MyGoals.tsx, apps/client/src/components/compounds/goal/goal.module.scss, apps/client/src/components/compounds/transactionHistory/TransactionHistory.tsx, apps/client/src/components/compounds/transactionHistory/transactionHistory.module.scss, apps/client/src/pages/Dashboard/Home.tsx, apps/client/src/pages/Dashboard/chartAndUpcoming/index.tsx, apps/client/src/pages/Landing/HowIsWork/HowIsWork.module.scss, apps/client/src/pages/Landing/HowIsWork/index.tsx, apps/server/src/backgroundJobs/emailTasks/index.ts, apps/server/src/backgroundJobs/emailTasks/queues.ts, apps/server/src/controllers/userControllers/authUsers.ts
=> fix: fix CI format and format existing codebase

apps/client/src/contexts/authContext.tsx
=> feat: add update auth context state function

apps/client/src/pages/Landing/HowIsWork/HowIsWork.module.scss, apps/client/src/pages/Landing/HowIsWork/index.tsx
correction of how it work section 
---
---
---
=> fix: CU-86bwj087w/Landing---How-it-works-Section-3

apps/client/src/components/elements/Button/button.module.scss, apps/client/src/components/elements/Button/index.tsx, apps/client/src/pages/Auth/ResetPassword/index.tsx, apps/client/src/pages/Auth/ResetPassword/layout.tsx, apps/client/src/pages/Auth/ResetPassword/requests.ts, apps/server/src/controllers/userControllers/authUsers.ts, apps/server/src/models/users.ts
-Implemented forgot-reset password
- button disabled after sending first request to avoid multiple http request
- count down of 30s was added to bring the button back active
---
Link :[CU-86bxc2ah4](<https://app.clickup.com/t/86bxc2ah4>)
---
---
**Test Coverage**
=> Cu 86bxc2ah4/fe forget reset password

apps/server/src/constants/index.ts, apps/server/src/controllers/userControllers/getUserTransactionHistory.ts, apps/server/src/models/transactions.ts, apps/server/src/routes/v1/users.ts
This feature queries the Transactions table & fetches the the five most recent transactions of a user.The response contains the details of each transaction including the users name, the amount transacted, the user's group title and the date of the transaction  ---
---
---
=> Cu 86bwmd18t/transaction history endpoint

apps/server/src/controllers/userControllers/getUpcomingActivities.ts, apps/server/src/routes/v1/users.ts
Paginated upcoming activities endpoint.
How to test:
- Add dummy data to your local db using the `createGroup` function. With the data you've created, you can use them to test the pagination function.
---
---
---
=> Cu 86bx0njw8/be paginate upcoming activities endpoint return 5 items per page starting from most recent

apps/client/src/components/compounds/TransactionDetails/ResponsiveTable.module.scss, apps/client/src/components/compounds/TransactionDetails/ResponsiveTable.tsx, package.json
=> Cu 86bwt2tfa/fe fix transaction

apps/server/src/constants/httpStatusCode.ts, apps/server/src/controllers/userControllers/getUserProfileDetails.ts
=> fix: update httphelper

apps/server/package.json, apps/server/src/backgroundJobs/walletTasks/jobs.ts, apps/server/src/config/env.ts, apps/server/src/controllers/paymentsController/fundGroupSavingsWallet.ts, apps/server/src/controllers/paymentsController/fundPersonalSavingsWallet.ts, apps/server/src/controllers/paymentsController/index.ts, apps/server/src/controllers/userControllers/getUserTransactionHistory.ts, apps/server/src/models/association.ts, apps/server/src/models/transactions.ts, apps/server/src/models/walletEarnings.ts, apps/server/src/routes/v1/payments.ts, apps/server/src/routes/v1/users.ts, apps/server/src/utils/betweenSatSun.ts, apps/server/src/utils/helpers.ts, apps/server/src/utils/hocs/withPaginate.ts, apps/server/src/utils/validators/index.ts
I added an endpoint that funds the personal group savings wallet from the global wallet.I also accepted the changes made to the transaction history endpoint.
---
---
---
=> Cu 86bx0nh1v/be be fund personal group savings wallet from global wallet

apps/server/src/constants/httpStatusCode.ts, apps/server/src/controllers/userControllers/getUserTransactionHistory.ts
fix response key not camel case
---
---
---
- create a transaction by adding funds
- call /users/transactionHistory
=> fix: update function to camelCase

apps/client/src/components/elements/DropBoxInput/index.tsx, apps/client/src/components/elements/DropBoxInput/styles.module.scss
- repositioned the upload's text and remove button
---
---
---
=> fix: reposition text and button

apps/server/src/app.ts
=> fix: remove force

apps/server/src/app.ts, apps/server/src/backgroundJobs/walletTasks/jobs.ts, apps/server/src/controllers/groupControllers/createGroup.ts, apps/server/src/controllers/paymentsController/fundWallet.ts, apps/server/src/controllers/paymentsController/helpers.ts, apps/server/src/controllers/targetControllers/createTargets.ts, apps/server/src/controllers/userControllers/wallets/getUserWallets.ts, apps/server/src/controllers/userControllers/wallets/walletBalances.ts, apps/server/src/models/groupMembers.ts, apps/server/src/models/groupWallet.ts, apps/server/src/models/targetWallets.ts, apps/server/src/models/targets.ts, apps/server/src/models/transactions.ts, apps/server/src/models/userWallets.ts, apps/server/src/routes/v1/payments.ts, apps/server/src/utils/validators/index.ts
This PR:
- Updates userWallet model to the current model design
-  Updates all endpoints affected by userWallet model updates(fundWallet, walletJob, getWalletBalances, getUserWallets)
-  Updates walletJob to only create Global Wallet on user signUp.
- Update groupWallet to current model design
- Updates all affected endpoints
- Updates targetWallet model to current model design
- Updates all affected endpoints.
---
---
---
=> fix: refactor user, target and group wallet models
